//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: AddRideLocation.proto

package si.um.feri.cycling_tracker_app.grpc;

@kotlin.jvm.JvmName("-initializeaddLocationRequest")
public inline fun addLocationRequest(block: si.um.feri.cycling_tracker_app.grpc.AddLocationRequestKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddLocationRequest =
  si.um.feri.cycling_tracker_app.grpc.AddLocationRequestKt.Dsl._create(si.um.feri.cycling_tracker_app.grpc.AddLocationRequest.newBuilder()).apply { block() }._build()
public object AddLocationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: si.um.feri.cycling_tracker_app.grpc.AddLocationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: si.um.feri.cycling_tracker_app.grpc.AddLocationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): si.um.feri.cycling_tracker_app.grpc.AddLocationRequest = _builder.build()

    /**
     * <code>int32 ride_id = 1;</code>
     */
    public var rideId: kotlin.Int
      @JvmName("getRideId")
      get() = _builder.getRideId()
      @JvmName("setRideId")
      set(value) {
        _builder.setRideId(value)
      }
    /**
     * <code>int32 ride_id = 1;</code>
     */
    public fun clearRideId() {
      _builder.clearRideId()
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public var timestamp: kotlin.Long
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * <code>double latitude = 3;</code>
     */
    public var latitude: kotlin.Double
      @JvmName("getLatitude")
      get() = _builder.getLatitude()
      @JvmName("setLatitude")
      set(value) {
        _builder.setLatitude(value)
      }
    /**
     * <code>double latitude = 3;</code>
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * <code>double longitude = 4;</code>
     */
    public var longitude: kotlin.Double
      @JvmName("getLongitude")
      get() = _builder.getLongitude()
      @JvmName("setLongitude")
      set(value) {
        _builder.setLongitude(value)
      }
    /**
     * <code>double longitude = 4;</code>
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun si.um.feri.cycling_tracker_app.grpc.AddLocationRequest.copy(block: si.um.feri.cycling_tracker_app.grpc.AddLocationRequestKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddLocationRequest =
  si.um.feri.cycling_tracker_app.grpc.AddLocationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

