//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: AddRideLocation.proto

package si.um.feri.cycling_tracker_app.grpc;

@kotlin.jvm.JvmName("-initializeaddLocationResponse")
public inline fun addLocationResponse(block: si.um.feri.cycling_tracker_app.grpc.AddLocationResponseKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddLocationResponse =
  si.um.feri.cycling_tracker_app.grpc.AddLocationResponseKt.Dsl._create(si.um.feri.cycling_tracker_app.grpc.AddLocationResponse.newBuilder()).apply { block() }._build()
public object AddLocationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: si.um.feri.cycling_tracker_app.grpc.AddLocationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: si.um.feri.cycling_tracker_app.grpc.AddLocationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): si.um.feri.cycling_tracker_app.grpc.AddLocationResponse = _builder.build()

    /**
     * <code>int32 isUploaded = 1;</code>
     */
    public var isUploaded: kotlin.Int
      @JvmName("getIsUploaded")
      get() = _builder.getIsUploaded()
      @JvmName("setIsUploaded")
      set(value) {
        _builder.setIsUploaded(value)
      }
    /**
     * <code>int32 isUploaded = 1;</code>
     */
    public fun clearIsUploaded() {
      _builder.clearIsUploaded()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun si.um.feri.cycling_tracker_app.grpc.AddLocationResponse.copy(block: si.um.feri.cycling_tracker_app.grpc.AddLocationResponseKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddLocationResponse =
  si.um.feri.cycling_tracker_app.grpc.AddLocationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

