//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: AddRide.proto

package si.um.feri.cycling_tracker_app.grpc;

@kotlin.jvm.JvmName("-initializeaddRideRequest")
public inline fun addRideRequest(block: si.um.feri.cycling_tracker_app.grpc.AddRideRequestKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddRideRequest =
  si.um.feri.cycling_tracker_app.grpc.AddRideRequestKt.Dsl._create(si.um.feri.cycling_tracker_app.grpc.AddRideRequest.newBuilder()).apply { block() }._build()
public object AddRideRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: si.um.feri.cycling_tracker_app.grpc.AddRideRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: si.um.feri.cycling_tracker_app.grpc.AddRideRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): si.um.feri.cycling_tracker_app.grpc.AddRideRequest = _builder.build()

    /**
     * <code>int32 ride_id = 1;</code>
     */
    public var rideId: kotlin.Int
      @JvmName("getRideId")
      get() = _builder.getRideId()
      @JvmName("setRideId")
      set(value) {
        _builder.setRideId(value)
      }
    /**
     * <code>int32 ride_id = 1;</code>
     */
    public fun clearRideId() {
      _builder.clearRideId()
    }

    /**
     * <code>uint64 timeStart = 2;</code>
     */
    public var timeStart: kotlin.Long
      @JvmName("getTimeStart")
      get() = _builder.getTimeStart()
      @JvmName("setTimeStart")
      set(value) {
        _builder.setTimeStart(value)
      }
    /**
     * <code>uint64 timeStart = 2;</code>
     */
    public fun clearTimeStart() {
      _builder.clearTimeStart()
    }

    /**
     * <code>uint64 timeStop = 3;</code>
     */
    public var timeStop: kotlin.Long
      @JvmName("getTimeStop")
      get() = _builder.getTimeStop()
      @JvmName("setTimeStop")
      set(value) {
        _builder.setTimeStop(value)
      }
    /**
     * <code>uint64 timeStop = 3;</code>
     */
    public fun clearTimeStop() {
      _builder.clearTimeStop()
    }

    /**
     * <code>uint64 duration = 4;</code>
     */
    public var duration: kotlin.Long
      @JvmName("getDuration")
      get() = _builder.getDuration()
      @JvmName("setDuration")
      set(value) {
        _builder.setDuration(value)
      }
    /**
     * <code>uint64 duration = 4;</code>
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }

    /**
     * <code>int32 user_id = 5;</code>
     */
    public var userId: kotlin.Int
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>int32 user_id = 5;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun si.um.feri.cycling_tracker_app.grpc.AddRideRequest.copy(block: si.um.feri.cycling_tracker_app.grpc.AddRideRequestKt.Dsl.() -> kotlin.Unit): si.um.feri.cycling_tracker_app.grpc.AddRideRequest =
  si.um.feri.cycling_tracker_app.grpc.AddRideRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

