// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddRideLocation.proto

package si.um.feri.cycling_tracker_app.grpc;

public interface AddLocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:si.um.feri.cycling_tracker_app.grpc.AddLocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ride_id = 1;</code>
   * @return The rideId.
   */
  int getRideId();

  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>double latitude = 3;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 4;</code>
   * @return The longitude.
   */
  double getLongitude();
}
