// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddRideLocation.proto

package si.um.feri.cycling_tracker_app.grpc;

public final class AddRideLocation {
  private AddRideLocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AddRideLocation.proto\022#si.um.feri.cycl" +
      "ing_tracker_app.grpc\"]\n\022AddLocationReque" +
      "st\022\017\n\007ride_id\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\004\022\020" +
      "\n\010latitude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\")\n\023A" +
      "ddLocationResponse\022\022\n\nisUploaded\030\001 \001(\0052\241" +
      "\001\n\026AddRideLocationService\022\206\001\n\017addRideLoc" +
      "ation\0227.si.um.feri.cycling_tracker_app.g" +
      "rpc.AddLocationRequest\0328.si.um.feri.cycl" +
      "ing_tracker_app.grpc.AddLocationResponse" +
      "\"\000B\tP\001Z\005/Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationRequest_descriptor,
        new java.lang.String[] { "RideId", "Timestamp", "Latitude", "Longitude", });
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_si_um_feri_cycling_tracker_app_grpc_AddLocationResponse_descriptor,
        new java.lang.String[] { "IsUploaded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
