// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddRide.proto

package si.um.feri.cycling_tracker_app.grpc;

public interface AddRideRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:si.um.feri.cycling_tracker_app.grpc.AddRideRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ride_id = 1;</code>
   * @return The rideId.
   */
  int getRideId();

  /**
   * <code>uint64 timeStart = 2;</code>
   * @return The timeStart.
   */
  long getTimeStart();

  /**
   * <code>uint64 timeStop = 3;</code>
   * @return The timeStop.
   */
  long getTimeStop();

  /**
   * <code>uint64 duration = 4;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>int32 user_id = 5;</code>
   * @return The userId.
   */
  int getUserId();
}
