// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddRide.proto

package si.um.feri.cycling_tracker_app.grpc;

public final class AddRide {
  private AddRide() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAddRide.proto\022#si.um.feri.cycling_trac" +
      "ker_app.grpc\"i\n\016AddRideRequest\022\017\n\007ride_i" +
      "d\030\001 \001(\005\022\021\n\ttimeStart\030\002 \001(\004\022\020\n\010timeStop\030\003" +
      " \001(\004\022\020\n\010duration\030\004 \001(\004\022\017\n\007user_id\030\005 \001(\005\"" +
      "%\n\017AddRideResponse\022\022\n\nisUploaded\030\001 \001(\0052\210" +
      "\001\n\016AddRideService\022v\n\007addRide\0223.si.um.fer" +
      "i.cycling_tracker_app.grpc.AddRideReques" +
      "t\0324.si.um.feri.cycling_tracker_app.grpc." +
      "AddRideResponse\"\000B\tP\001Z\005/Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideRequest_descriptor,
        new java.lang.String[] { "RideId", "TimeStart", "TimeStop", "Duration", "UserId", });
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_si_um_feri_cycling_tracker_app_grpc_AddRideResponse_descriptor,
        new java.lang.String[] { "IsUploaded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
