// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddRide.proto

package si.um.feri.cycling_tracker_app.grpc;

public interface AddRideResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:si.um.feri.cycling_tracker_app.grpc.AddRideResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 isUploaded = 1;</code>
   * @return The isUploaded.
   */
  int getIsUploaded();
}
